Swift 5 support
RxSwiftCommunity/NSObject-Rx pull request #67
Opened 2019-05-02 12:30 UTC by fassko

Adding RxSwift 5.0.x support

2019-05-02 15:02 UTC, freak4pc requested changes

2019-05-02 15:02 UTC, freak4pc commented on Changelog.md
> +4.5.0
This needs to be 5.0.0

2019-05-02 19:46 UTC, ashfurrow commented on Changelog.md
> +4.5.0
```suggestion
5.0.0
```

2019-05-03 07:19 UTC, fassko commented on Changelog.md
> +4.5.0
Thanks, I changed in podspec as well.

2019-05-03 09:32 UTC, freak4pc reviewed
LGTM!

2019-05-03 09:32 UTC, merged

2019-05-03 09:37 UTC, freak4pc commented
@fassko Thanks for you work here! I just realized this is one of the only projects where we didn't update to Circle v2 from v1 - so CI just doesn't run anymore. Is there any chance you could find the time to do that? It should be mostly straightforward

2019-05-03 09:40 UTC, fassko commented
@freak4pc Sure I will create an issue and do it. I have done it for some of my projects.

2019-05-03 09:41 UTC, fassko commented
I just discovered that there is an issue created by me :D

https://github.com/RxSwiftCommunity/NSObject-Rx/issues/62

2019-05-03 09:41 UTC, freak4pc commented
_self-five to past @fassko_