Build in Circle CI 2.0
RxSwiftCommunity/NSObject-Rx pull request #68
Opened 2019-05-03 09:55 UTC by fassko

2019-05-03 21:02 UTC, freak4pc commented
Hey @fassko, thanks ! 
Not sure why but a rebase isn't possible (conflicting) - could you rebase on top of master? 

Also, I'm wondering why are there so many changes if all was needed is a new config? Is it the Pods removal I imagine/\

2019-05-03 21:04 UTC, freak4pc requested changes

2019-05-03 21:04 UTC, freak4pc commented on .circleci/config.yml
> +           cron: "0 0 * * *"
I don't think we need a nightly build for this repo...

2019-05-04 05:54 UTC, fassko commented
@freak4pc I had to remove Pods because there is some problem with other machines like Circle CI. Also it will make repo smaller.

I will try to rebase.

2019-05-04 09:00 UTC, fassko commented
I did rebase from master.

2019-05-04 09:47 UTC, freak4pc commented
Uhm doesn't seem like it ... can you take a look again? Worst case I can just merge it but I prefer a rebase: 
![image](https://user-images.githubusercontent.com/605076/57177202-b4c66380-6e6a-11e9-9935-08fbf12858e1.png)

2019-05-04 09:47 UTC, merged

2019-05-04 09:50 UTC, freak4pc commented
Not sure why but this is failing on master. Any thoughts? https://circleci.com/gh/RxSwiftCommunity/NSObject-Rx/62

2019-05-04 15:31 UTC, fassko commented
Hmm something is weird with keys. Do you have access to settings of this repo? To see if key which is in Circle is valid?

2019-05-04 16:10 UTC, freak4pc commented
OK, passing now. Thanks @fassko ! 

I'm a bit confused by two things:

1. Why do we need both CocoaPods and Carthage for CI? More specifically it seems like Carthage isn't being used at all. Is it there just to confirm it's building?

2. Seems we're only testing iOS... Would be good to do the other supported platforms as well.

2019-05-04 16:16 UTC, fassko commented
1. I think you're right Carthage is needed only for local development if you want to edit Xcode project. I will remove it to speed up the build.

2. True, this is very good recommendation.

I will create issues for both of these things otherwise I forget things quickly. :P